const jsonEN = {
  main_nav_1: 'Services',
  main_nav_2: 'Products',
  main_nav_3: 'Company',
  main_nav_mobile_1: 'Services',
  main_nav_mobile_2: 'Products',
  main_nav_mobile_3: 'Company',
  sub_nav_1_1: 'Industrial Project Management',
  sub_nav_1_2: 'Production Efficiency and Improvement',
  sub_nav_1_3: 'Quality Control',
  sub_nav_1_4: 'Financial Consulting and Investment Studies',
  sub_nav_1_5: 'Process Improvement and Strategy Support',
  sub_nav_1_6: 'Procurement Support',
  sub_nav_1_7: 'Management Consulting',
  sub_nav_1_8: 'Implementation Support',
  sub_nav_2_1: 'Conveying Systems',
  sub_nav_2_2: 'Special Machines and Individual Parts',
  sub_nav_2_3: 'Industrial Hardware and Software Applications',
  sub_nav_2_4: 'CNC and 3D Services',
  sub_nav_2_5: 'Processing Equipment',
  sub_nav_mobile_1_1: 'Industrial Project Management',
  sub_nav_mobile_1_2: 'Production Efficiency and Improvement',
  sub_nav_mobile_1_3: 'Quality Control',
  sub_nav_mobile_1_4: 'Financial Consulting and Investment Studies',
  sub_nav_mobile_1_5: 'Process Improvement and Strategy Support',
  sub_nav_mobile_1_6: 'Procurement Support',
  sub_nav_mobile_1_7: 'Management Consulting',
  sub_nav_mobile_1_8: 'Implementation Support',
  sub_nav_mobile_2_1: 'Conveying Systems',
  sub_nav_mobile_2_2: 'Special Machines and Individual Parts',
  sub_nav_mobile_2_3: 'Industrial Hardware and Software Applications',
  sub_nav_mobile_2_4: 'CNC and 3D Services',
  sub_nav_mobile_2_5: 'Processing Equipment',
  nav_btn: 'Inquire',
  main_section_holder_title: 'Maximizing Efficiency, Minimizing Costs.',
  about_us_title: 'ABOUT US',
  main_section_holder_description:
    'TEGUM is your Partner in Industrial Project Management, Production Enhancement and Strategic Process Innovation. We draw on decades of cross-industry experience to deliver real-world specialized solutions.',
  about_us_title_1: 'Industrial Expertise',
  about_us_description_1:
    'TEGUM leverages deep industry expertise to tackle complex challenges. We focus on production efficiency and process improvement to offer tailored solutions to meet your unique business needs.',
  about_us_title_2: 'Strategic Excellence',
  about_us_description_2: `Our strategic support empowers your operational efficiency, stay agile and make well-informed decisions. We're your go-to source for optimizing procurement, quality control, and supply chain management.`,
  about_us_title_3: 'Growth and Prosperity',
  about_us_description_3: `With a dedication to compliance, reliable management consulting and insightful financial guidance, we're here to drive your business's growth and profitability for a future of sustainable success.`,
  what_we_do_title_1: '01 - Project Management',
  what_we_do_title_2: '02 - Consulting Services',
  what_we_do_title_3: '03 - Custom Manufacturing',
  what_we_do_small_title: 'WHAT WE DO',
  services_small_title: 'SERVICES',
  hovered_btn_1: 'Hire us',
  hovered_btn_2: 'Hire us',
  hovered_btn_3: 'Hire us',
  what_we_do_description_1:
    'Optimizing projects with agility and innovation, we guarantee on-time and bud- get-friendly delivery. Specializing in production efficiency, our services encompass procurement, layout design, Six Sigma methodologies, and total productive main- tenance. Committed to ensuring quality and regulatory compliance, we uphold industry norms, delivering excellence in every process.',
  what_we_do_description_2:
    'Enhance operations, cut costs, and ensure sustainability. Our team tackles challenges in supply chain, procurement, and daily operations with innovative solutions. Boost profitability through strategic goal support and efficient processes.',
  what_we_do_description_3:
    'Custom-designed conveying systems, specialized machine production, and preci- sion-designed parts. Our services encompass customized industrial hardware and software solutions, high-precision CNC machining, and 3D printing. From intake to packaging, our offerings ensure process efficiency for confectionery, snacks, and more.',
  option_holder_1_title_1: 'Industrial Project Management',
  option_holder_1_title_2: 'Production Efficiency and Improvement',
  option_holder_1_title_3: 'Quality Control',
  option_holder_1_title_4: 'Financial Consulting and Investment Studies',
  option_holder_2_title_1: 'Process Improvement and Strategy Support',
  option_holder_2_title_2: 'Procurement Support',
  option_holder_2_title_3: 'Management Consulting',
  option_holder_2_title_4: 'Implementation Support',
  option_holder_3_title_1: 'Conveying Systems',
  option_holder_3_title_2: 'Special Machines and Individual Parts',
  option_holder_3_title_3: 'Industrial Hardware and Software Applications',
  option_holder_3_title_4: 'CNC and 3D Services',
  option_holder_3_title_5: 'Processing Equipment',
  expertise_holder_number_main: 'Your industrial partner for a future of sustainable success.',
  expertise_holder_description_main: 'OUR EXPERTISE',
  expertise_holder_title_1: 'Machine Engineering',
  expertise_holder_title_2: 'Process Engineering',
  expertise_holder_title_3: 'FMCG Industry',
  expertise_holder_title_4: 'Turnkey Consultancy',
  expertise_holder_title_5: 'Project Lifecycle Expertise',
  expertise_holder_title_6: 'Operational Excellence',
  expertise_holder_title_7: 'Industrial Internet of Things',
  expertise_holder_title_8: 'Investment Studies',
  expertise_holder_title_9: 'Conveying Systems',
  expertise_holder_description_1:
    'Specialized knowledge in industrial project management, production efficiency, and process improvement.',
  expertise_holder_description_2:
    'Comprehensive strategy support to enhance your operations and ensure a competitive edge in the market.',
  expertise_holder_description_3:
    'Optimize sourcing, category management, and quality control to drive efficiency and quality.',
  expertise_holder_description_4:
    'Compliance with norms and standards guarantees the highest level of quality and safety in your processes.',
  expertise_holder_description_5:
    'Our management consulting and implementation support guarantee smooth objectives execution.',
  expertise_holder_description_6:
    'Fnancial consulting and investment studies will help make informed decisions that maximize returns',
  challenges_title: 'Tackle complex industrial challenges.',
  challenges_btn: 'Get started',
  footer_nav_1: 'Services',
  footer_nav_2: 'Products',
  footer_nav_3: 'Company',
  footer_contact_address: 'Address: Pop Lukina 2/II/15, 15000 Sabac, Serbia',
  footer_contact_phone: 'Phone:',
  page_contact_address: 'Address: Pop Lukina 2/II/15, 15000 Sabac, Serbia',
  page_contact_phone: 'Phone:',
  footer_btn: 'Contact us',
  footer_rights_lang:'©2023. All rights reserved.',
  main_section_fcis_holder_title: 'Financial Consulting and Investment Studies',
  main_section_fcis_holder_description: 'Delve into the depth of financial expertise with our comprehensive suite of services, providing meticulous financial analysis and detailed investment studies. Our goal is to empower you, offering insights that go beyond numbers, guiding you to make informed decisions strategically aligned to maximize your return on investment and drive sustained financial growth.',
  tegum_services_fcis_small_title: 'TEGUM Services',
  tegum_services_fcis_title: 'Comprehensive Solutions for Strategic Growth',
  tegum_services_fcis_holder_title_1: 'Financial Consulting',
  tegum_services_fcis_holder_description_1:
    ' Our industry and production financial consulting services are crafted to empower businesses with strategic financial management. Our seasoned consultants work closely with you to understand the nuances of your industry and production processes. From budget optimization and cost-effective resource allocation to risk mitigation strategies, we provide tailored financial guidance that aligns with your unique business goals. Whether you are aiming to streamline operations, enhance profitability, or navigate financial challenges, our consulting services are your key to sustainable financial success.',
  tegum_services_fcis_holder_options_1_title: 'Needs Assessment:',
  tegum_services_fcis_holder_options_1_description:
    ' Thorough evaluation of your industry and production financial landscape. Identification of specific financial challenges and opportunities unique to your business.',
  tegum_services_fcis_holder_options_2_title: 'Customized Financial Strategies:',
  tegum_services_fcis_holder_options_2_description:
    ' Tailoring financial strategies to align with your business objectives. Implementing cost optimization measures and resource allocation plans.',
  tegum_services_fcis_holder_options_3_title: 'Risk Mitigation:',
  tegum_services_fcis_holder_options_3_description:
    'Comprehensive risk analysis to anticipate and mitigate potential financial challenges. Development of risk management strategies for enhanced financial resilience. ',

  tegum_services_fcis_holder_options_4_title: 'Operational Efficiency Enhancement:',
  tegum_services_fcis_holder_options_4_description:
    'Streamlining operational processes to improve efficiency. Identifying areas for cost-effective resource utilization.',
  tegum_services_fcis_holder_title_2: 'Investment Studies',
  tegum_services_fcis_holder_description_2: `In the dynamic landscape of industry and production, informed decision-making is crucial. Our investment studies offer a detailed analysis that goes beyond traditional financial evaluations. `,
  tegum_services_fcis_holder_description_2_1:
    'We delve into market trends, potential risks, and growth opportunities specific to your industry. Whether you are considering expanding your production capabilities, introducing new technologies, or venturing into new markets, our studies provide a strategic roadmap. Backed by data-driven insights, we equip you with the knowledge needed to make confident and impactful investment decisions. Our goal is to ensure that your investments not only align with your current business objectives but also pave the way for long-term success and growth in the industry and production sector.',
  get_started_fcis_small_title: 'GET STARTED',
  get_started_fcis_title:
    'Tackle complex challenges in industrial project management, production efficiency, and process improvement.',
  get_started_fcis_btn: 'Get started',
  main_section_contact_holder_title: `Let's meet your unique business needs.`,
  form_name: 'Your Name',
  form_email: 'Email (required)',
  form_subject: 'Subject',
  form_comment: 'Message',
  main_section_about_us_holder_title:
    'Tegum was founded in 2002, focusing initially on mechanical engineering within the chemical and process industries.',
  history_subtitle:
    'As Tegum grew, it expanded its services into the design and execution of thermo-technical installations and equipment for various industrial sectors.',
  history_title: '20 Years of Expertise',
  history_description_1:
    'With over two decades of experience, we established ourselves as an expert in the industry, particularly in the food and beverage sector, while maintaining its core competency in thermo-technical installations.',
  history_description_2:
    'Industry 4.0 Integration: Tegum embraces the possibilities of the Industry 4.0 revolution, integrating its diverse knowledge and expertise to ensure continuous growth and provide top-quality consulting services to its clients.',
  main_section_piss_holder_title: 'Process Improvement and Strategy Support',
  main_section_piss_holder_description: `Our consulting team focuses on enhancing your operations, improving processes, and supporting your strategic goals. We analyze processes, identify challenges, and implement innovative solutions. We offer support in supply chain efficiency, automation, and innovation to improve performance and drive profitability.`,
  tegum_services_piss_small_title: 'TEGUM Services',
  tegum_services_piss_title: 'Relying less on the Financial consulting and grid',
  get_started_piss_small_title: 'GET STARTED',
  get_started_piss_title:
    'Tackle complex challenges in industrial project management, production efficiency, and process improvement.',
  get_started_piss_btn: 'Get started',
  main_section_ipm_holder_title: 'Industrial Project Management',
  main_section_ipm_holder_description: `Our team excels in guiding industrial projects, ensuring production efficiency, maintenance, and control. We provide agile, proactive, and innovative solutions to deliver projects on time and within budget.`,
  tegum_services_ipm_small_title: '',
  tegum_services_ipm_title: '',
  tegum_services_ipm_holder_title_1: '',
  tegum_services_ipm_holder_description_1: '',
  tegum_services_ipm_holder_options_1_title: '',
  tegum_services_ipm_holder_options_1_description: '',
  tegum_services_ipm_holder_options_2_title: '',
  tegum_services_ipm_holder_options_2_description: '',
  tegum_services_ipm_holder_options_3_title: '',
  tegum_services_ipm_holder_options_3_description: '',
  tegum_services_ipm_holder_options_4_title: '',
  tegum_services_ipm_holder_options_4_description: '',
  tegum_services_ipm_holder_title_2: '',
  tegum_services_ipm_holder_description_2: ``,
  tegum_services_ipm_holder_description_2_1: '',
  get_started_ipm_small_title: '',
  get_started_ipm_title: '',
  get_started_ipm_btn: 'Get started',
  main_section_pei_holder_title: 'Production Efficiency and Improvement',
  main_section_pei_holder_description: `At our core, we specialize in elevating production efficiency and ensuring top-notch quality through a comprehensive range of services, encompassing procurement, meticulous layout design, adept utilization of Six Sigma methodologies, and the implementation of total productive maintenance strategies.`,
  tegum_services_pei_small_title: '',
  tegum_services_pei_title: '',
  tegum_services_pei_holder_title_1: '',
  tegum_services_pei_holder_description_1: '',
  tegum_services_pei_holder_options_1_title: '',
  tegum_services_pei_holder_options_1_description: '',
  tegum_services_pei_holder_options_2_title: '',
  tegum_services_pei_holder_options_2_description: '',
  tegum_services_pei_holder_options_3_title: '',
  tegum_services_pei_holder_options_3_description: '',
  tegum_services_pei_holder_options_4_title: '',
  tegum_services_pei_holder_options_4_description: '',
  tegum_services_pei_holder_title_2: '',
  tegum_services_pei_holder_description_2: ``,
  tegum_services_pei_holder_description_2_1: '',
  get_started_pei_small_title: '',
  get_started_pei_title: '',
  get_started_pei_btn: 'Get started',
  main_section_qc_holder_title: 'Quality Control',
  main_section_qc_holder_description:
    'Ensuring processes meet industry norms and standards, maintaining the highest quality and regulatory compliance.',
  tegum_services_qc_small_title: '',
  tegum_services_qc_title: '',
  tegum_services_qc_holder_title_1: '',
  tegum_services_qc_holder_description_1: '',
  tegum_services_qc_holder_options_1_title: '',
  tegum_services_qc_holder_options_1_description: '',
  tegum_services_qc_holder_options_2_title: '',
  tegum_services_qc_holder_options_2_description: '',
  tegum_services_qc_holder_options_3_title: '',
  tegum_services_qc_holder_options_3_description: '',
  tegum_services_qc_holder_options_4_title: '',
  tegum_services_qc_holder_options_4_description: '',
  tegum_services_qc_holder_title_2: '',
  tegum_services_qc_holder_description_2: ``,
  tegum_services_qc_holder_description_2_1: '',
  get_started_qc_small_title: '',
  get_started_qc_title: '',
  get_started_qc_btn: 'Get started',
  main_section_ps_holder_title: 'Procurement Support',
  main_section_ps_holder_description:
    'Optimize procurement through services such as sourcing, category management, quality control, audits, and supplier development. Cut costs, ensure quality, and minimize operational disruption.',
  tegum_services_ps_small_title: '',
  tegum_services_ps_title: '',
  tegum_services_ps_holder_title_1: '',
  tegum_services_ps_holder_description_1: '',
  tegum_services_ps_holder_options_1_title: '',
  tegum_services_ps_holder_options_1_description: '',
  tegum_services_ps_holder_options_2_title: '',
  tegum_services_ps_holder_options_2_description: '',
  tegum_services_ps_holder_options_3_title: '',
  tegum_services_ps_holder_options_3_description: '',
  tegum_services_ps_holder_options_4_title: '',
  tegum_services_ps_holder_options_4_description: '',
  tegum_services_ps_holder_title_2: '',
  tegum_services_ps_holder_description_2: ``,
  tegum_services_ps_holder_description_2_1: '',
  get_started_ps_small_title: '',
  get_started_ps_title: '',
  get_started_ps_btn: 'Get started',
  main_section_mc_holder_title: 'Management Consulting',
  main_section_mc_holder_description:'Cover a wide range of business areas, including process improvement, risk assessment, and innovation in daily operations. Focus on delivering sustainability in your operations.',
  tegum_services_mc_small_title: '',
  tegum_services_mc_title: '',
  tegum_services_mc_holder_title_1: '',
  tegum_services_mc_holder_description_1: '',
  tegum_services_mc_holder_options_1_title: '',
  tegum_services_mc_holder_options_1_description: '',
  tegum_services_mc_holder_options_2_title: '',
  tegum_services_mc_holder_options_2_description: '',
  tegum_services_mc_holder_options_3_title: '',
  tegum_services_mc_holder_options_3_description: '',
  tegum_services_mc_holder_options_4_title: '',
  tegum_services_mc_holder_options_4_description: '',
  tegum_services_mc_holder_title_2: '',
  tegum_services_mc_holder_description_2: ``,
  tegum_services_mc_holder_description_2_1: '',
  get_started_mc_small_title: '',
  get_started_mc_title: '',
  get_started_mc_btn: 'Get started',
  main_section_is_holder_title: 'Implementation Support',
  main_section_is_holder_description: `Our team offers hands-on support in tackling process variability, process control, and preventing ergonomics problems, ensuring the sustainability of your processes while innovating daily operations.`,
  tegum_services_is_small_title: '',
  tegum_services_is_title: '',
  tegum_services_is_holder_title_1: '',
  tegum_services_is_holder_description_1: '',
  tegum_services_is_holder_options_1_title: '',
  tegum_services_is_holder_options_1_description: '',
  tegum_services_is_holder_options_2_title: '',
  tegum_services_is_holder_options_2_description: '',
  tegum_services_is_holder_options_3_title: '',
  tegum_services_is_holder_options_3_description: '',
  tegum_services_is_holder_options_4_title: '',
  tegum_services_is_holder_options_4_description: '',
  tegum_services_is_holder_title_2: '',
  tegum_services_is_holder_description_2: ``,
  tegum_services_is_holder_description_2_1: '',
  get_started_is_small_title: '',
  get_started_is_title: '',
  get_started_is_btn: 'Get started',
  main_section_cs_holder_title: 'Conveying Systems',
  main_section_cs_holder_description: `Custom design and fabrication of conveying systems and other internal transportation and storage solutions for manufacturing and warehouse facilities. We provide systems for loading, unloading, and transport.`,
  tegum_services_cs_small_title: '',
  tegum_services_cs_title: '',
  tegum_services_cs_holder_title_1: '',
  tegum_services_cs_holder_description_1: '',
  tegum_services_cs_holder_options_1_title: '',
  tegum_services_cs_holder_options_1_description: '',
  tegum_services_cs_holder_options_2_title: '',
  tegum_services_cs_holder_options_2_description: '',
  tegum_services_cs_holder_options_3_title: '',
  tegum_services_cs_holder_options_3_description: '',
  tegum_services_cs_holder_options_4_title: '',
  tegum_services_cs_holder_options_4_description: '',
  tegum_services_cs_holder_title_2: '',
  tegum_services_cs_holder_description_2: ``,
  tegum_services_cs_holder_description_2_1: '',
  get_started_cs_small_title: '',
  get_started_cs_title: '',
  get_started_cs_btn: 'Get started',
  main_section_smp_holder_title: 'Special Machines and Individual Parts',
  main_section_smp_holder_description: `Tailored production of specialized machines for small and medium-sized enterprises, designed to meet specific client needs and purposes.
  Precision design and manufacturing of specific, individual parts based on samples. Our services include identifying design issues and offering effective solutions.`,
  tegum_services_smp_small_title: '',
  tegum_services_smp_title: '',
  tegum_services_smp_holder_title_1: '',
  tegum_services_smp_holder_description_1: '',
  tegum_services_smp_holder_options_1_title: '',
  tegum_services_smp_holder_options_1_description: '',
  tegum_services_smp_holder_options_2_title: '',
  tegum_services_smp_holder_options_2_description: '',
  tegum_services_smp_holder_options_3_title: '',
  tegum_services_smp_holder_options_3_description: '',
  tegum_services_smp_holder_options_4_title: '',
  tegum_services_smp_holder_options_4_description: '',
  tegum_services_smp_holder_title_2: '',
  tegum_services_smp_holder_description_2: ``,
  tegum_services_smp_holder_description_2_1: '',
  get_started_smp_small_title: '',
  get_started_smp_title: '',
  get_started_smp_btn: 'Get started',
  main_section_ihsa_holder_title: 'Industrial Hardware and Software Applications',
  main_section_ihsa_holder_description: `Development of customized industrial hardware and software solutions, including OEE software, facility management systems, IIoT and temperature control software, crafted to match clients' requirements (REVIND).`,
  tegum_services_ihsa_small_title: '',
  tegum_services_ihsa_title: '',
  tegum_services_ihsa_holder_title_1: '',
  tegum_services_ihsa_holder_description_1: '',
  tegum_services_ihsa_holder_options_1_title: '',
  tegum_services_ihsa_holder_options_1_description: '',
  tegum_services_ihsa_holder_options_2_title: '',
  tegum_services_ihsa_holder_options_2_description: '',
  tegum_services_ihsa_holder_options_3_title: '',
  tegum_services_ihsa_holder_options_3_description: '',
  tegum_services_ihsa_holder_options_4_title: '',
  tegum_services_ihsa_holder_options_4_description: '',
  tegum_services_ihsa_holder_title_2: '',
  tegum_services_ihsa_holder_description_2: ``,
  tegum_services_ihsa_holder_description_2_1: '',
  get_started_ihsa_small_title: '',
  get_started_ihsa_title: '',
  get_started_ihsa_btn: 'Get started',
  main_section_cnc_holder_title: 'CNC and 3D Services',
  main_section_cnc_holder_description: `High-precision CNC machining and 3D printing services. We offer 3D printing and part fabrication in our machine workshop equipped with CNC machining centers.`,
  tegum_services_cnc_small_title: '',
  tegum_services_cnc_title: '',
  tegum_services_cnc_holder_title_1: '',
  tegum_services_cnc_holder_description_1: '',
  tegum_services_cnc_holder_options_1_title: '',
  tegum_services_cnc_holder_options_1_description: '',
  tegum_services_cnc_holder_options_2_title: '',
  tegum_services_cnc_holder_options_2_description: '',
  tegum_services_cnc_holder_options_3_title: '',
  tegum_services_cnc_holder_options_3_description: '',
  tegum_services_cnc_holder_options_4_title: '',
  tegum_services_cnc_holder_options_4_description: '',
  tegum_services_cnc_holder_title_2: '',
  tegum_services_cnc_holder_description_2: ``,
  tegum_services_cnc_holder_description_2_1: '',
  get_started_cnc_small_title: '',
  get_started_cnc_title: '',
  get_started_cnc_btn: 'Get started',
  main_section_pe_holder_title: 'Processing Equipment',
  main_section_pe_holder_description: `Specialized equipment for the confectionery, snacks, fruit and vegetable processing, and packaging industries, as well as HVAC systems. Our offerings cover the entire process, from receiving fresh produce through cleaning, transportation, cutting, blanching, freezing, to packaging of the final products.`,
  tegum_services_pe_small_title: '',
  tegum_services_pe_title: '',
  tegum_services_pe_holder_title_1: '',
  tegum_services_pe_holder_description_1: '',
  tegum_services_pe_holder_options_1_title: '',
  tegum_services_pe_holder_options_1_description: '',
  tegum_services_pe_holder_options_2_title: '',
  tegum_services_pe_holder_options_2_description: '',
  tegum_services_pe_holder_options_3_title: '',
  tegum_services_pe_holder_options_3_description: '',
  tegum_services_pe_holder_options_4_title: '',
  tegum_services_pe_holder_options_4_description: '',
  tegum_services_pe_holder_title_2: '',
  tegum_services_pe_holder_description_2: ``,
  tegum_services_pe_holder_description_2_1: '',
  get_started_pe_small_title: '',
  get_started_pe_title: '',
  get_started_pe_btn: 'Get started',
};

const jsonSR = {
  main_nav_1: 'Usluge',
  main_nav_2: 'Proizvodi',
  main_nav_3: 'Kompanija',
  main_nav_mobile_1: 'Usluge',
  main_nav_mobile_2: 'Proizvodi',
  main_nav_mobile_3: 'Kompanija',
  sub_nav_1_1: 'Upravljanje industrijskim projektima',
  sub_nav_1_2: 'Efikasnost i poboljšanje proizvodnje',
  sub_nav_1_3: 'Kontrola kvaliteta',
  sub_nav_1_4: 'Finansijski konsalting i investicione studije',
  sub_nav_1_5: 'Poboljšanje procesa i podrška strategije',
  sub_nav_1_6: 'Podrška nabavkama',
  sub_nav_1_7: 'Konsultanti za menadžment',
  sub_nav_1_8: 'Podrška za implementaciju',
  sub_nav_2_1: 'Sistemi za transport',
  sub_nav_2_2: 'Specijalne mašine i delovi',
  sub_nav_2_3: 'Industrijske hardverske i softverske aplikacije',
  sub_nav_2_4: 'CNC i 3D usluge',
  sub_nav_2_5: 'Oprema za obradu',
  sub_nav_mobile_1_1: 'Upravljanje industrijskim projektima',
  sub_nav_mobile_1_2: 'Efikasnost i poboljšanje proizvodnje',
  sub_nav_mobile_1_3: 'Kontrola kvaliteta',
  sub_nav_mobile_1_4: 'Finansijski konsalting i investicione studije',
  sub_nav_mobile_1_5: 'Poboljšanje procesa i podrška strategije',
  sub_nav_mobile_1_6: 'Podrška nabavkama',
  sub_nav_mobile_1_7: 'Konsultanti za menadžment',
  sub_nav_mobile_1_8: 'Podrška za implementaciju',
  sub_nav_mobile_2_1: 'Sistemi za transport',
  sub_nav_mobile_2_2: 'Specijalne mašine i delovi',
  sub_nav_mobile_2_3: 'Industrijske hardverske i softverske aplikacije',
  sub_nav_mobile_2_4: 'CNC i 3D usluge',
  sub_nav_mobile_2_5: 'Oprema za obradu',
  nav_btn: 'Raspitaj se',
  main_section_holder_title: 'Maksimiziranje efikasnosti, minimiziranje troškova',
  about_us_title: 'O NAMA',
  main_section_holder_description:
    'TEGUM je vaš partner u upravljanju industrijskim projektima, unapređenju proizvodnje i strateškim inovacijama procesa. Oslanjamo se na višedecenijsko iskustvo u različitim industrijama da bismo pružili specijalizovana rešenja u stvarnom svetu.',
  about_us_title_1: 'Industrijske Ekpertise',
  about_us_description_1:
    'TEGUM koristi duboku stručnost u industriji da bi se uhvatio u koštac sa složenim izazovima. Fokusiramo se na efikasnost proizvodnje i poboljšanje procesa kako bismo ponudili rešenja po meri koja će zadovoljiti vaše jedinstvene poslovne potrebe  ',
  about_us_title_2: 'Strateška izvrsnost',
  about_us_description_2:
    'Naša strateška podrška osnažuje vašu operativnu efikasnost, ostanite agilni i donosite odluke sa dobrim informacijama. Mi smo vaš glavni izvor za optimizaciju nabavke, kontrole kvaliteta i upravljanja lancem snabdevanja.',
  about_us_title_3: 'Rast i prosperitet',
  about_us_description_3:
    'Sa posvećenošću usklađenosti, pouzdanim savetovanjem o menadžmentu i pronicljivim finansijskim uputstvima, mi smo tu da pokrenemo rast i profitabilnost vašeg poslovanja za budućnost održivog uspeha.',
  what_we_do_title_1: '01 - Upravljanje projektima',
  what_we_do_title_2: '02 - Konsultantske usluge',
  what_we_do_title_3: '03 - Izrada po meri',
  what_we_do_small_title: 'ŠTA RADIMO',
  hovered_btn_1: 'Unajmi nas',
  hovered_btn_2: 'Unajmi nas',
  hovered_btn_3: 'Unajmi nas',
  services_small_title: 'USLUGE',
  what_we_do_description_1:
    'Optimizirajući projekte agilnošću i inovativnošću, garantujemo isporuku na vreme i ekonomičnu isporuku. Specijalizovani za efikasnost proizvodnje, naše usluge obuhvataju nabavku, dizajn rasporeda, Sik Sigma metodologije i ukupno produktivno održavanje. Posvećeni obezbeđivanju kvaliteta i usklađenosti sa propisima, mi se pridržavamo industrijskih normi, pružajući izvrsnost u svakom procesu.',
  what_we_do_description_2:
    'Poboljšajte operacije, smanjite troškove i osigurajte održivost. Naš tim se nosi sa izazovima u lancu snabdevanja, nabavci i svakodnevnim operacijama sa inovativnim rešenjima. Povećajte profitabilnost kroz podršku strateškim ciljevima i efikasne procese.',
  what_we_do_description_3:
    'Prilagođeno dizajnirani transportni sistemi, specijalizovana proizvodnja mašina i precizno dizajnirani delovi. Naše usluge obuhvataju prilagođena industrijska hardverska i softverska rešenja, visoko preciznu CNC mašinsku obradu i 3D štampanje. Od unosa do pakovanja, naša ponuda obezbeđuje efikasnost procesa za konditorske proizvode, grickalice i još mnogo toga.',
  option_holder_1_title_1: 'Upravljanje industrijskim projektima',
  option_holder_1_title_2: 'Efikasnost i poboljšanje proizvodnje',
  option_holder_1_title_3: 'Kontrola kvaliteta',
  option_holder_1_title_4: 'Finansijski konsalting i investicione studije',
  option_holder_2_title_1: 'Poboljšanje procesa i podrška strategije',
  option_holder_2_title_2: 'Podrška nabavkama',
  option_holder_2_title_3: 'Konsultanti za upravljanje',
  option_holder_2_title_4: 'Podrška za implementaciju',
  option_holder_3_title_1: 'Sistemi za transport',
  option_holder_3_title_2: 'Specijalne mašine i delovi',
  option_holder_3_title_3: 'Industrijske hardverske i softverske aplikacije',
  option_holder_3_title_4: 'CNC i 3D usluge',
  option_holder_3_title_5: 'Oprema za obradu',
  expertise_holder_number_main: 'Vaš industrijski partner za budućnost održivog uspeha.',
  expertise_holder_description_main: 'NAŠA STRUČNOST',
  expertise_holder_title_1: 'Mašinsko inženjerstvo',
  expertise_holder_title_2: 'Procesni inženjering',
  expertise_holder_title_3: 'FMCG industrija',
  expertise_holder_title_4: 'Konsultantske usluge po sistemu ključ u ruke',
  expertise_holder_title_5: 'Stručnost životnog ciklusa projekta',
  expertise_holder_title_6: 'Operativna izvrsnost',
  expertise_holder_title_7: 'Industrijski internet stvari',
  expertise_holder_title_8: 'Investicione studije',
  expertise_holder_title_9: 'Sistemi za transport',
  expertise_holder_description_1:
    'Specijalizovano znanje u upravljanju industrijskim projektima, efikasnosti proizvodnje i poboljšanju procesa.',
  expertise_holder_description_2:
    'Sveobuhvatna podrška za strategiju za poboljšanje vašeg poslovanja i osiguravanje konkurentske prednosti na tržištu.',
  expertise_holder_description_3:
    'Optimizujte izvore, upravljanje kategorijama i kontrolu kvaliteta da biste podstakli efikasnost i kvalitet.',
  expertise_holder_description_4:
    'Usklađenost sa normama i standardima garantuje najviši nivo kvaliteta i bezbednosti u vašim procesima.',
  expertise_holder_description_5:
    'Naše savetovanje o menadžmentu i podrška implementaciji garantuju nesmetano izvršavanje ciljeva.',
  expertise_holder_description_6:
    'Finansijski konsalting i investicione studije će pomoći u donošenju informisanih odluka koje maksimiziraju prinose',
  challenges_title: 'Rešite se složenih industrijskih izazova.',
  challenges_btn: 'Počni',
  footer_nav_1: 'Usluge',
  footer_nav_2: 'Proizvodi',
  footer_nav_3: 'Kompanija',
  footer_contact_address: 'Adresa: Pop Lukina 2/II/15, 15000 Šabac, Srbija',
  footer_contact_phone: 'Telefon:',
  page_contact_address: 'Adresa: Pop Lukina 2/II/15, 15000 Šabac, Srbija',
  page_contact_phone: 'Telefon:',
  footer_btn: 'Kontaktiraj nas',
  footer_rights_lang:'©2023. Sva prava zadržana.',
  main_section_fcis_holder_title: 'Finansijski konsalting i investicione studije',
  main_section_fcis_holder_description: 'Uđite u dubinu finansijske ekspertize pomoću našeg sveobuhvatnog paketa usluga, pružajući preciznu finansijsku analizu i detaljne investicione studije. Naš cilj je da vas osnažimo, nudeći uvide koji prevazilaze brojke, vodeći vas da donosite informisane odluke koje su strateški usklađene kako biste maksimizirali povrat ulaganja i podstakli održivi finansijski rast.',
  tegum_services_fcis_small_title: 'TEGUM Usluge',
  tegum_services_fcis_title: 'Sveobuhvatna rešenja za strateški rast',
  tegum_services_fcis_holder_title_1: 'Finansijski Konsalting',
  tegum_services_fcis_holder_description_1:
    'Naše usluge finansijskog konsaltinga u industriji i proizvodnji su napravljene da osnaže preduzeća sa strateškim finansijskim upravljanjem. Naši iskusni konsultanti blisko sarađuju sa vama kako bi razumeli nijanse vaše industrije i proizvodnih procesa. Od optimizacije budžeta i isplative alokacije resursa do strategija za smanjenje rizika, pružamo prilagođene finansijske smernice koje su u skladu sa vašim jedinstvenim poslovnim ciljevima. Bez obzira da li želite da pojednostavite poslovanje, povećate profitabilnost ili se nosite sa finansijskim izazovima, naše konsultantske usluge su vaš ključ za održivi finansijski uspeh.',
  tegum_services_fcis_holder_options_1_title: 'Procena potreba:',
  tegum_services_fcis_holder_options_1_description:
    'Detaljna procena finansijske situacije vaše industrije i proizvodnje. Identifikacija specifičnih finansijskih izazova i prilika jedinstvenih za vaše poslovanje.',
  tegum_services_fcis_holder_options_2_title: 'Prilagođene finansijske strategije:',
  tegum_services_fcis_holder_options_2_description:
    'Prilagođavanje finansijskih strategija u skladu sa vašim poslovnim ciljevima. Sprovođenje mera optimizacije troškova i planova raspodele resursa.',
  tegum_services_fcis_holder_options_3_title: 'Ublažavanje rizika:',
  tegum_services_fcis_holder_options_3_description:
    'Sveobuhvatna analiza rizika za predviđanje i ublažavanje potencijalnih finansijskih izazova. Razvoj strategija upravljanja rizicima za povećanu finansijsku otpornost.',
  tegum_services_fcis_holder_options_4_title: 'Poboljšanje operativne efikasnosti:',
  tegum_services_fcis_holder_options_4_description:
    'Racionalizacija operativnih procesa radi poboljšanja efikasnosti. Identifikovanje oblasti za isplativo korišćenje resursa.',
  tegum_services_fcis_holder_title_2: 'Investicione studije',
  tegum_services_fcis_holder_description_2:
    'U dinamičnom pejzažu industrije i proizvodnje, informisano donošenje odluka je ključno. Naše investicione studije nude detaljnu analizu koja prevazilazi tradicionalne finansijske procene.',
  tegum_services_fcis_holder_description_2_1:
    'Udubljujemo se u tržišne trendove, potencijalne rizike i mogućnosti rasta specifične za vašu industriju. Bez obzira da li razmišljate o proširenju svojih proizvodnih mogućnosti, uvođenju novih tehnologija ili ulasku na nova tržišta, naše studije pružaju stratešku mapu puta. Podržani uvidima zasnovanim na podacima, mi vas opremimo znanjem potrebnim za donošenje sigurnih i uticajnih odluka o ulaganju. Naš cilj je da obezbedimo da vaše investicije ne samo da budu u skladu sa vašim trenutnim poslovnim ciljevima, već i da utre put za dugoročni uspeh i rast u industriji i proizvodnom sektoru.',
  get_started_fcis_small_title: 'POČNI',
  get_started_fcis_title:
    'Riješite se složenih izazova u upravljanju industrijskim projektima, efikasnosti proizvodnje i poboljšanju procesa.',
  get_started_fcis_btn: 'Počni',
  main_section_contact_holder_title: 'Hajde da ispunimo vaše jedinstvene poslovne potrebe.',
  form_name: 'Ime',
  form_email: 'Email (obavezno)',
  form_subject: 'Tema',
  form_comment: 'Poruka',
  main_section_about_us_holder_title:
    'Tegum je osnovan 2002. godine, u početku se fokusirajući na mašinstvo u okviru hemijske i procesne industrije.',
  history_subtitle:
    'Kako je Tegum rastao, proširio je svoje usluge na projektovanje i izvođenje termotehničkih instalacija i opreme za različite industrijske sektore.',
  history_title: '20 godina stručnosti',
  history_description_1:
    'Sa više od dve decenije iskustva, etablirali smo se kao ekspert u industriji, posebno u sektoru hrane i pića, zadržavajući svoju osnovnu kompetenciju u termotehničkim instalacijama.',
  history_description_2:
    'Integracija industrije 4.0: Tegum prihvata mogućnosti revolucije industrije 4.0, integrišući svoje raznovrsno znanje i stručnost kako bi osigurao kontinuirani rast i pružio vrhunske konsultantske usluge svojim klijentima.',
  main_section_piss_holder_title: 'Poboljšanje procesa i podrška strategije',
  main_section_piss_holder_description: `Naš konsultantski tim se fokusira na unapređenje vašeg poslovanja, poboljšanje procesa i podršku vašim strateškim ciljevima. Analiziramo procese, identifikujemo izazove i implementiramo inovativna rešenja. Nudimo podršku u efikasnosti lanca snabdevanja, automatizaciji i inovacijama za poboljšanje performansi i povećanje profitabilnosti.`,
  tegum_services_piss_small_title: 'TEGUM usluge',
  tegum_services_piss_title: 'Manje oslanjanje na finansijski konsalting i mrežu',
  get_started_piss_small_title: 'POČNI',
  get_started_piss_title:
    'Riješite se složenih izazova u upravljanju industrijskim projektima, efikasnosti proizvodnje i poboljšanju procesa.',
  get_started_piss_btn: 'Počni',
  main_section_ipm_holder_title: 'Upravljanje industrijskim projektima',
  main_section_ipm_holder_description: `Naš tim se ističe u vođenju industrijskih projekata, obezbeđujući efikasnost proizvodnje, održavanje i kontrolu. Pružamo agilna, proaktivna i inovativna rešenja za isporuku projekata na vreme i u okviru budžeta.`,
  tegum_services_ipm_small_title: '',
  tegum_services_ipm_title: '',
  tegum_services_ipm_holder_title_1: '',
  tegum_services_ipm_holder_description_1: '',
  tegum_services_ipm_holder_options_1_title: '',
  tegum_services_ipm_holder_options_1_description: '',
  tegum_services_ipm_holder_options_2_title: '',
  tegum_services_ipm_holder_options_2_description: '',
  tegum_services_ipm_holder_options_3_title: '',
  tegum_services_ipm_holder_options_3_description: '',
  tegum_services_ipm_holder_options_4_title: '',
  tegum_services_ipm_holder_options_4_description: '',
  tegum_services_ipm_holder_title_2: '',
  tegum_services_ipm_holder_description_2: ``,
  tegum_services_ipm_holder_description_2_1: '',
  get_started_ipm_small_title: '',
  get_started_ipm_title: '',
  get_started_ipm_btn: 'Počni',
  main_section_pei_holder_title: 'Efikasnost i poboljšanje proizvodnje',
  main_section_pei_holder_description: `U suštini, mi smo specijalizovani za podizanje efikasnosti proizvodnje i obezbeđivanje vrhunskog kvaliteta kroz sveobuhvatan spektar usluga, koji obuhvataju nabavku, pedantan dizajn izgleda, vešto korišćenje Sik Sigma metodologija i implementaciju ukupnih strategija produktivnog održavanja.`,
  tegum_services_pei_small_title: '',
  tegum_services_pei_title: '',
  tegum_services_pei_holder_title_1: '',
  tegum_services_pei_holder_description_1: '',
  tegum_services_pei_holder_options_1_title: '',
  tegum_services_pei_holder_options_1_description: '',
  tegum_services_pei_holder_options_2_title: '',
  tegum_services_pei_holder_options_2_description: '',
  tegum_services_pei_holder_options_3_title: '',
  tegum_services_pei_holder_options_3_description: '',
  tegum_services_pei_holder_options_4_title: '',
  tegum_services_pei_holder_options_4_description: '',
  tegum_services_pei_holder_title_2: '',
  tegum_services_pei_holder_description_2: ``,
  tegum_services_pei_holder_description_2_1: '',
  get_started_pei_small_title: '',
  get_started_pei_title: '',
  get_started_pei_btn: 'Počni',
  main_section_qc_holder_title: 'Kontrola kvaliteta',
  main_section_qc_holder_description:
    'Obezbeđujemo da procesi ispunjavaju industrijske norme i standarde, održavajući najviši kvalitet i usklađenost sa propisima.',
  tegum_services_qc_small_title: '',
  tegum_services_qc_title: '',
  tegum_services_qc_holder_title_1: '',
  tegum_services_qc_holder_description_1: '',
  tegum_services_qc_holder_options_1_title: '',
  tegum_services_qc_holder_options_1_description: '',
  tegum_services_qc_holder_options_2_title: '',
  tegum_services_qc_holder_options_2_description: '',
  tegum_services_qc_holder_options_3_title: '',
  tegum_services_qc_holder_options_3_description: '',
  tegum_services_qc_holder_options_4_title: '',
  tegum_services_qc_holder_options_4_description: '',
  tegum_services_qc_holder_title_2: '',
  tegum_services_qc_holder_description_2: ``,
  tegum_services_qc_holder_description_2_1: '',
  get_started_qc_small_title: '',
  get_started_qc_title: '',
  get_started_qc_btn: 'Počni',
  main_section_ps_holder_title: 'Podrška nabavci',
  main_section_ps_holder_description:
    'Optimizujte nabavku kroz usluge poput pronalaženja izvora, upravljanja kategorijama, kontrole kvaliteta, revizija i razvoja dobavljača. Smanjite troškove, obezbedite kvalitet i minimizirajte operativne poremećaje.',
  tegum_services_ps_small_title: '',
  tegum_services_ps_title: '',
  tegum_services_ps_holder_title_1: '',
  tegum_services_ps_holder_description_1: '',
  tegum_services_ps_holder_options_1_title: '',
  tegum_services_ps_holder_options_1_description: '',
  tegum_services_ps_holder_options_2_title: '',
  tegum_services_ps_holder_options_2_description: '',
  tegum_services_ps_holder_options_3_title: '',
  tegum_services_ps_holder_options_3_description: '',
  tegum_services_ps_holder_options_4_title: '',
  tegum_services_ps_holder_options_4_description: '',
  tegum_services_ps_holder_title_2: '',
  tegum_services_ps_holder_description_2: ``,
  tegum_services_ps_holder_description_2_1: '',
  get_started_ps_small_title: '',
  get_started_ps_title: '',
  get_started_ps_btn: 'Počni',
  main_section_mc_holder_title: 'Menadžment konsalting',
  main_section_mc_holder_description:'Pokriva širok spektar poslovnih oblasti, uključujući poboljšanje procesa, procenu rizika i inovacije u svakodnevnim operacijama. Fokusirajte se na pružanje održivosti u vašim operacijama.',
  tegum_services_mc_small_title: '',
  tegum_services_mc_title: '',
  tegum_services_mc_holder_title_1: '',
  tegum_services_mc_holder_description_1: '',
  tegum_services_mc_holder_options_1_title: '',
  tegum_services_mc_holder_options_1_description: '',
  tegum_services_mc_holder_options_2_title: '',
  tegum_services_mc_holder_options_2_description: '',
  tegum_services_mc_holder_options_3_title: '',
  tegum_services_mc_holder_options_3_description: '',
  tegum_services_mc_holder_options_4_title: '',
  tegum_services_mc_holder_options_4_description: '',
  tegum_services_mc_holder_title_2: '',
  tegum_services_mc_holder_description_2: ``,
  tegum_services_mc_holder_description_2_1: '',
  get_started_mc_small_title: '',
  get_started_mc_title: '',
  get_started_mc_btn: 'Počni',
  main_section_is_holder_title: 'Podrška implementaciji',
  main_section_is_holder_description: `Naš tim nudi praktičnu podršku u rešavanju varijabilnosti procesa, kontroli procesa i sprečavanju problema ergonomije, obezbeđujući održivost vaših procesa dok inovirate svakodnevne operacije.`,
  tegum_services_is_small_title: '',
  tegum_services_is_title: '',
  tegum_services_is_holder_title_1: '',
  tegum_services_is_holder_description_1: '',
  tegum_services_is_holder_options_1_title: '',
  tegum_services_is_holder_options_1_description: '',
  tegum_services_is_holder_options_2_title: '',
  tegum_services_is_holder_options_2_description: '',
  tegum_services_is_holder_options_3_title: '',
  tegum_services_is_holder_options_3_description: '',
  tegum_services_is_holder_options_4_title: '',
  tegum_services_is_holder_options_4_description: '',
  tegum_services_is_holder_title_2: '',
  tegum_services_is_holder_description_2: ``,
  tegum_services_is_holder_description_2_1: '',
  get_started_is_small_title: '',
  get_started_is_title: '',
  get_started_is_btn: 'Počni',
  main_section_cs_holder_title: 'Transportni sistemi',
  main_section_cs_holder_description: `Dizajniranje i izrada transportnih sistema po meri i drugih internih rešenja za transport i skladištenje za proizvodne i skladišne objekte. Pružamo sisteme za utovar, istovar i transport.`,
  tegum_services_cs_small_title: '',
  tegum_services_cs_title: '',
  tegum_services_cs_holder_title_1: '',
  tegum_services_cs_holder_description_1: '',
  tegum_services_cs_holder_options_1_title: '',
  tegum_services_cs_holder_options_1_description: '',
  tegum_services_cs_holder_options_2_title: '',
  tegum_services_cs_holder_options_2_description: '',
  tegum_services_cs_holder_options_3_title: '',
  tegum_services_cs_holder_options_3_description: '',
  tegum_services_cs_holder_options_4_title: '',
  tegum_services_cs_holder_options_4_description: '',
  tegum_services_cs_holder_title_2: '',
  tegum_services_cs_holder_description_2: ``,
  tegum_services_cs_holder_description_2_1: '',
  get_started_cs_small_title: '',
  get_started_cs_title: '',
  get_started_cs_btn: 'Počni',
  main_section_smp_holder_title: 'Specijalne mašine i delovi',
  main_section_smp_holder_description: `Proizvodnja specijalizovanih mašina po meri za mala i srednja preduzeća, dizajnirana da zadovolje specifične potrebe i namene klijenata.
  Precizno projektovanje i izrada specifičnih, pojedinačnih delova na osnovu uzoraka. Naše usluge uključuju identifikaciju problema dizajna i nuđenje efikasnih rešenja.`,
  tegum_services_smp_small_title: '',
  tegum_services_smp_title: '',
  tegum_services_smp_holder_title_1: '',
  tegum_services_smp_holder_description_1: '',
  tegum_services_smp_holder_options_1_title: '',
  tegum_services_smp_holder_options_1_description: '',
  tegum_services_smp_holder_options_2_title: '',
  tegum_services_smp_holder_options_2_description: '',
  tegum_services_smp_holder_options_3_title: '',
  tegum_services_smp_holder_options_3_description: '',
  tegum_services_smp_holder_options_4_title: '',
  tegum_services_smp_holder_options_4_description: '',
  tegum_services_smp_holder_title_2: '',
  tegum_services_smp_holder_description_2: ``,
  tegum_services_smp_holder_description_2_1: '',
  get_started_smp_small_title: '',
  get_started_smp_title: '',
  get_started_smp_btn: 'Počni',
  main_section_ihsa_holder_title: 'Industrijske aplikacije hardvera i softvera',
  main_section_ihsa_holder_description: `Razvoj prilagođenih industrijskih hardverskih i softverskih rešenja, uključujući OEE softver, sisteme za upravljanje objektima, IIoT i softver za kontrolu temperature, napravljen da odgovara zahtevima klijenata (REVIND).`,
  tegum_services_ihsa_small_title: '',
  tegum_services_ihsa_title: '',
  tegum_services_ihsa_holder_title_1: '',
  tegum_services_ihsa_holder_description_1: '',
  tegum_services_ihsa_holder_options_1_title: '',
  tegum_services_ihsa_holder_options_1_description: '',
  tegum_services_ihsa_holder_options_2_title: '',
  tegum_services_ihsa_holder_options_2_description: '',
  tegum_services_ihsa_holder_options_3_title: '',
  tegum_services_ihsa_holder_options_3_description: '',
  tegum_services_ihsa_holder_options_4_title: '',
  tegum_services_ihsa_holder_options_4_description: '',
  tegum_services_ihsa_holder_title_2: '',
  tegum_services_ihsa_holder_description_2: ``,
  tegum_services_ihsa_holder_description_2_1: '',
  get_started_ihsa_small_title: '',
  get_started_ihsa_title: '',
  get_started_ihsa_btn: 'Počni',
  main_section_cnc_holder_title: 'CNC i 3D Usluge',
  main_section_cnc_holder_description: `Usluge visokoprecizne CNC obrade i 3D štampanja. Nudimo 3D štampanje i izradu delova u našoj mašinskoj radionici opremljenoj CNC obradnim centrima.`,
  tegum_services_cnc_small_title: '',
  tegum_services_cnc_title: '',
  tegum_services_cnc_holder_title_1: '',
  tegum_services_cnc_holder_description_1: '',
  tegum_services_cnc_holder_options_1_title: '',
  tegum_services_cnc_holder_options_1_description: '',
  tegum_services_cnc_holder_options_2_title: '',
  tegum_services_cnc_holder_options_2_description: '',
  tegum_services_cnc_holder_options_3_title: '',
  tegum_services_cnc_holder_options_3_description: '',
  tegum_services_cnc_holder_options_4_title: '',
  tegum_services_cnc_holder_options_4_description: '',
  tegum_services_cnc_holder_title_2: '',
  tegum_services_cnc_holder_description_2: ``,
  tegum_services_cnc_holder_description_2_1: '',
  get_started_cnc_small_title: '',
  get_started_cnc_title: '',
  get_started_cnc_btn: 'Počni',
  main_section_pe_holder_title: 'Oprema za obradu',
  main_section_pe_holder_description: `Specijalizovana oprema za industriju konditorskih proizvoda, grickalica, preradu voća i povrća i ambalažnu industriju, kao i HVAC sisteme. Naša ponuda pokriva ceo proces, od prijema svežih proizvoda preko čišćenja, transporta, sečenja, blanširanja, zamrzavanja, do pakovanja finalnih proizvoda.`,
  tegum_services_pe_small_title: '',
  tegum_services_pe_title: '',
  tegum_services_pe_holder_title_1: '',
  tegum_services_pe_holder_description_1: '',
  tegum_services_pe_holder_options_1_title: '',
  tegum_services_pe_holder_options_1_description: '',
  tegum_services_pe_holder_options_2_title: '',
  tegum_services_pe_holder_options_2_description: '',
  tegum_services_pe_holder_options_3_title: '',
  tegum_services_pe_holder_options_3_description: '',
  tegum_services_pe_holder_options_4_title: '',
  tegum_services_pe_holder_options_4_description: '',
  tegum_services_pe_holder_title_2: '',
  tegum_services_pe_holder_description_2: ``,
  tegum_services_pe_holder_description_2_1: '',
  get_started_pe_small_title: '',
  get_started_pe_title: '',
  get_started_pe_btn: 'Počni',
};

$(document).on('click', '.en', function (event) {
  localStorage.setItem('lang', 'en');
  // setTimeout(() => location.reload(), 100);
  window.location.href = window.location.href;
});

$(document).on('click', '.sr', function (event) {
  localStorage.setItem('lang', 'sr');
  // setTimeout(() => location.reload(), 100);
  window.location.href = window.location.href;
});

$(document).ready(function () {
  const isMobileTablet = window.innerWidth < 992;

  if (localStorage.getItem('lang') === null) {
    localStorage.setItem('lang', 'en');
    $('.sr').addClass('active');
    setTimeout(() => (window.location.href = window.location.href), 100);
  } else {
    const lang = localStorage.getItem('lang');
    const jsonData = lang === 'sr' ? jsonSR : jsonEN;
    const activeButton = lang === 'sr' ? '.en' : '.sr';
    setTimeout(() => {
      $(activeButton).addClass('active');
    }, 300);

    for (let key in jsonData) {
      setTimeout(() => {
        const element = document.querySelector('.' + key);
        if (lang === 'sr') {
          $('.form_btn_lang').attr('value', 'Pošalji');
        } else {
          $('.form_btn_lang').attr('value', 'Send');
        }
        if (element) {
          element.textContent = jsonData[key];
        }
      }, 300);
    }
  }
});
